FROM microsoft/dotnet:2.1-sdk
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["leadz.api/Leadz.Api.csproj", "leadz.api/"]

RUN dotnet restore "leadz.api/Leadz.Api.csproj"
COPY . .
WORKDIR "/src/leadz.api"
RUN dotnet build --no-restore "Leadz.Api.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]