// <auto-generated />

using System;
using Leadz.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Leadz.Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180219135347_1st")]
    partial class _1st
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("LeadzApi.Model.Canvasser", b =>
                {
                    b.Property<string>("CanvasserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.Property<long>("PhoneNo");

                    b.Property<string>("Role");

                    b.Property<int>("TeamId");

                    b.HasKey("CanvasserId");

                    b.ToTable("Canvasser");
                });

            modelBuilder.Entity("LeadzApi.Model.Lead", b =>
                {
                    b.Property<Guid>("LeadId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AppointmentDateTime");

                    b.Property<string>("CanvasserId");

                    b.Property<int>("HouseNumber");

                    b.Property<int>("NoOfDoors");

                    b.Property<int>("NoOfWindows");

                    b.Property<string>("Notes");

                    b.Property<string>("PostCode");

                    b.Property<string>("Status");

                    b.Property<string>("Street");

                    b.Property<string>("Surname");

                    b.Property<string>("Town");

                    b.HasKey("LeadId");

                    b.HasIndex("CanvasserId");

                    b.ToTable("Lead");
                });

            modelBuilder.Entity("LeadzApi.Model.Lead", b =>
                {
                    b.HasOne("LeadzApi.Model.Canvasser", "Canvasser")
                        .WithMany("Leads")
                        .HasForeignKey("CanvasserId");
                });
#pragma warning restore 612, 618
        }
    }
}
